// <auto-generated />
namespace KinderChatServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class flags4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(flags4));
        
        string IMigrationMetadata.Id
        {
            get { return "201504271814092_flags4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
